use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use thiserror::Error;

use crate::rpc::{RpcCredentials, RpcError};
use crate::storage::verify_private_file;
use zeroize::Zeroizing;

const MAX_LOGIN_BYTES: u64 = 512;

#[derive(Debug, Error)]
pub enum CredentialFileError {
    #[error("runtime directory must be absolute")]
    RelativeRuntimeDirectory,
    #[error("generated RPC credential file is not available yet")]
    NotReady,
    #[error("generated RPC credential file is missing, unsafe, or inaccessible")]
    UnsafeFile,
    #[error("generated RPC credential file exceeds its size limit")]
    TooLarge,
    #[error("generated RPC credential file is malformed")]
    InvalidContents,
}

/// Reads the login file generated by a managed `ryo-wallet-rpc` process. The
/// returned credentials remain Rust-only and redact their Debug representation.
pub fn read_generated_login(
    runtime_directory: &Path,
    rpc_port: u16,
) -> Result<RpcCredentials, CredentialFileError> {
    if !runtime_directory.is_absolute() {
        return Err(CredentialFileError::RelativeRuntimeDirectory);
    }
    let path = login_path(runtime_directory, rpc_port);
    let metadata = match fs::symlink_metadata(&path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err(CredentialFileError::NotReady);
        }
        Err(_) => return Err(CredentialFileError::UnsafeFile),
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(CredentialFileError::UnsafeFile);
    }
    if metadata.len() > MAX_LOGIN_BYTES {
        return Err(CredentialFileError::TooLarge);
    }
    let mut options = fs::OpenOptions::new();
    options.read(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt;
        use windows_sys::Win32::Storage::FileSystem::FILE_FLAG_OPEN_REPARSE_POINT;
        options.custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    }
    let file = options
        .open(&path)
        .map_err(|_| CredentialFileError::UnsafeFile)?;
    verify_private_file(&file).map_err(|_| CredentialFileError::UnsafeFile)?;
    let mut contents = Zeroizing::new(Vec::new());
    file.take(MAX_LOGIN_BYTES + 1)
        .read_to_end(&mut contents)
        .map_err(|_| CredentialFileError::UnsafeFile)?;
    if contents.len() > MAX_LOGIN_BYTES as usize {
        return Err(CredentialFileError::TooLarge);
    }
    let value = std::str::from_utf8(&contents).map_err(|_| CredentialFileError::InvalidContents)?;
    let (username, password) = value
        .split_once(':')
        .ok_or(CredentialFileError::InvalidContents)?;
    RpcCredentials::new(username.to_owned(), password.to_owned()).map_err(map_credential_error)
}

pub fn login_path(runtime_directory: &Path, rpc_port: u16) -> PathBuf {
    runtime_directory.join(format!("ryo-wallet-rpc.{rpc_port}.login"))
}

fn map_credential_error(_error: RpcError) -> CredentialFileError {
    CredentialFileError::InvalidContents
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    fn write_owner_only(path: &Path, contents: &[u8]) {
        fs::write(path, contents).unwrap();
        crate::storage::secure_file(path).unwrap();
    }

    #[test]
    fn reads_expected_generated_file_without_exposing_credentials() {
        let temp = tempfile::tempdir().unwrap();
        let path = login_path(temp.path(), 12345);
        write_owner_only(&path, b"ryo:generated-password");
        let credentials = read_generated_login(temp.path(), 12345).unwrap();
        assert_eq!(format!("{credentials:?}"), "RpcCredentials([REDACTED])");
    }

    #[test]
    fn rejects_unsafe_or_malformed_login_files() {
        let temp = tempfile::tempdir().unwrap();
        let path = login_path(temp.path(), 12345);
        assert!(matches!(
            read_generated_login(temp.path(), 12345),
            Err(CredentialFileError::NotReady)
        ));
        write_owner_only(&path, b"not-a-login");
        assert!(matches!(
            read_generated_login(temp.path(), 12345),
            Err(CredentialFileError::InvalidContents)
        ));
    }

    #[cfg(unix)]
    #[test]
    fn rejects_group_or_world_readable_login_file() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempfile::tempdir().unwrap();
        let path = login_path(temp.path(), 12345);
        fs::write(&path, b"ryo:generated-password").unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o644)).unwrap();
        assert!(matches!(
            read_generated_login(temp.path(), 12345),
            Err(CredentialFileError::UnsafeFile)
        ));
    }
}
